### PR TITLE
Add error handling

### PR DESCRIPTION
**Pull request by jordanwade**
Add error handling for GraphQL errors and Network errors.

### CODE REVIEW

**Comment by conrad-vanl** [comment]
So this is going to prevent errors from being thrown, and instead just logged to the console, correct?

Where are you seeing errors that are not being handled? I'm sure there are several - but I would think we should be handling errors at a more localized level or via `componentDidCatch` type stuff. There's also [`errorPolicy`s that we can set](https://www.apollographql.com/docs/react/data/error-handling/)

**Comment by jordanwade** [comment]
@conrad-vanl Yes, this would just log errors to the console. 

The reason I did this was as we are doing these integrations I'm not getting any helpful errors thrown or logged. The app would just be blank or it might show a card informing me something went wrong. But, I don't see anything helpful in log. So, debugging is pretty difficult. Maybe `errorPolicy` would be the answer.

Also, It would be really helpful if we could pair on one of these integrations so I can see how everything connects. Or more specifically work through a resolver/resolverMerge.

**Comment by jordanwade** [comment]
@conrad-vanl should I just close this PR and use `errorPolicy` and `componentDidCatch` instead as I come across unhandled errors?

**Comment by conrad-vanl** [comment]
@jordanwade my github notifications have been ignored the last 3 days, I apologize. My fault.

If you want to pair you are welcome to throw time on my calendar whenever and I'll hop on! I'd love to show you how everything works.

As far as errors - if you're using the [react native debugger](https://github.com/jhen0409/react-native-debugger) you should be able to right-click in the debugger window and select "Enable Network Inspect" which will give you network request logging:
Screen Shot 2020-03-27 at 9 24 00 AM

That's what I generally use to see errors.

However - I'm still not sure where you are seseing errors that aren't either throwing a RSOD or a rendered error card

**Comment by jordanwade** [comment]
Closing in favor of other error handling strategies.

**Pull request closed without merging**
