### PR TITLE
Select campus

### PR DESCRIPTION
**Pull request by vinnyjth**

### CODE REVIEW

**Comment by vinnyjth** [comment]
Any guesses on what I'll need to do in order to make the MapView screen use the dark mode?

**Comment by conrad-vanl** [comment]
> Any guesses on what I'll need to do in order to make the MapView screen use the dark mode?

Last time I looked it's not really possible right now, it's OS controlled. Best we could do right now is switch to using Google Maps and make a custom theme, which isn't worth doing.

https://github.com/react-native-community/react-native-maps/issues/754

https://stackoverflow.com/questions/23327985/mkmapview-night-mode-like-in-ios7-apple-maps

**Comment by vinnyjth** [comment]
@conrad-vanl This is now ready for review. I will need a core PR to fix the purple button on the mapview screen.

**Comment by conrad-vanl** [comment]
@vinnyjth this looks good! One thing I forgot to document in Basecamp:

they want to have an "Online Campus" option that is the first option on the list IF you don't have a campus within a set distance (I think 50 miles).

Mock for that:

Screen Shot 2020-05-06 at 10 21 45 AM

What do you think the effort is on this one? I think Christ Fellowship is doing that in their app somehow.

**Comment by vinnyjth** [comment]
Uh - I think it should be pretty easy. Should this be an actual option? Like your campus would change to “online campus”.

I can set this up in Rock and make it happen :)

**Comment by conrad-vanl** [comment]
@vinnyjth yeah your campus would be the "Online Campus". Although I don't think that's what they actually want to call it, but yes that would become your campus.

**Comment by vinnyjth** [comment]
@conrad-vanl this is done and ready for review again

**Pull request merged**
