### PR TITLE
chore: update awaken icon and image

### PR DESCRIPTION
**Pull request by nlewis84**

### CODE REVIEW

**Comment by nlewis84** [comment]
@jpowell Can I get an approval and merge on this? If you can give me write access to the repo, that would be awesome! Right now I can't even tag a reviewer. Thanks 🙏

**Review by gburgett — APPROVED** [review]

**Comment by gburgett** [comment]
@nlewis84 I just gave you write access

**Comment by gburgett** [comment]
@nlewis84 we got a last minute change from the Porch team, they'd like us to use this image instead:
https://watermarkchurch.sharepoint.com/sites/WM-DallasPorchTeam/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FWM%2DDallasPorchTeam%2FShared%20Documents%2FGeneral%2F6%2E%20Events%2FAWAKEN%2FAWAKEN%202022%2F03%2E%20Comms%20%26%20Creative%2FAwaken%202022%2FApp%2Fhero%2Epng&parent=%2Fsites%2FWM%2DDallasPorchTeam%2FShared%20Documents%2FGeneral%2F6%2E%20Events%2FAWAKEN%2FAWAKEN%202022%2F03%2E%20Comms%20%26%20Creative%2FAwaken%202022%2FApp&p=true&ga=1

Would you please change out the image and submit a new build to the app store?

**Comment by jpowell** [comment]
Here's a public link:

https://watermarkchurch.sharepoint.com/:i:/s/WM-DallasPorchTeam/EfiOkufWYnpDnbQ8WgL1K8QBxFzQzAQxPDS2I5G9xb4Sug?e=OxxpV8

**Pull request merged**
