### PR TITLE
Add location select to connect

### PR DESCRIPTION
**Pull request by jordanwade**
- [x] Click `Change` to change campus location (mapview)
- [x] Click `Campus Details` open a location page. An about page for the campus.
Simulator Screen Shot - iPhone 11 Pro Max - 2020-05-18 at 15 37 46
Simulator Screen Shot - iPhone 11 Pro Max - 2020-05-18 at 15 37 56

### CODE REVIEW

**Comment by jordanwade** [comment]
Just found the mock in figma. No need to review this yet...

**Comment by conrad-vanl** [comment]
Tapping the location card is supposed to open a location page, not a campus selector. There's a campus selector button above it though. I talked about this with @vinnyjth for a bit. Sorry it's not well defined!!

**Comment by jordanwade** [comment]
@vinnyjth what is the best way to expose a description for each location? I think that is all I need before this can be reviewed.

**Comment by conrad-vanl** [comment]
@jordanwade nice work on this. I made some tweaks based on some un-communicated design requirements, namely the client wanting to have a list of announcements on this "about campus" page as well. My fault for not having this well captured - I'm working on templates for Basecamp to do this better in the future.

**Pull request merged**
