### PR TITLE
Add onboarding flag to app storage

### PR DESCRIPTION
**Pull request by jordanwade**
#12 

This makes it so a user only sees Onboarding once.

To test:

- Open app (User should see Landing Screen)
- Go through onboarding
- Reload app (User should see Tabs screen)

A temporary Onboarding reset is in the connect tab. If you click the gear the next time you reload the app you should see the Landing Screen and onboarding flow. This will be removed before merge.
image

### CODE REVIEW

**Comment by conrad-vanl** [comment]
I didn't really _mean_ to approve this already, but the code is looking great!

**Comment by conrad-vanl** [comment]
I'd like to worko n testing it locally before we merge. Github won't let me take back my approval though

**Comment by jordanwade** [comment]
Cool, if you still want the ability to reset the async storage from the app you can work from this commit. https://github.com/Differential/theporch-apollos/pull/13/commits/d83c5606271bb59af8555c70a9276014f8c94b97

I just removed that async reset functionality from `UserAvatarHeader`.

**Comment by conrad-vanl** [comment]
Screen Shot 2020-03-09 at 1 06 47 PM

@jordanwade I get this error as soon as I try to start the app locally? Any ideas?

@vinnyjth when you have a moment, would you do a quick code glance on this, particularly the `OnboardingProvider` and LMK what you think, and whether this is a pattern you'd endorse us to start doing on client apps like this? I know previously we would've used something like apollo graphql client state, but that's kind of a pain. This is nice and fairly easy, but seems a little verbose to me, not that that is a deal breaker IMO. I just want insight from a long-term maintenance perspective and whether it's worth doing things like this.

**Comment by jordanwade** [comment]
@conrad-vanl I'm not sure. I'm trying to reproduce it on my machine with no luck. 

I wonder since I call dispatch with `useEffect` in the same file where the <Providers> are called there is something going on with a race condition...

**Comment by vinnyjth** [comment]
@conrad-vanl I'm 100% behind using the Provider API in place of the apollo client stuff, especially in client apps and places list this. I've been writing this way (but without hooks) on Willow and Core recently.

**Comment by jordanwade** [comment]
@vinnyjth when you have time can you test this branch and see if you get the same error as Conrad?

**Comment by conrad-vanl** [comment]
@jordanwade what prompted the eslint changes? I don't see that any linting is being done in my editor locally (may be my fault), just curious if related or not

**Comment by jordanwade** [comment]
@conrad-vanl yeah I was having the same issue no linting in my editor. So, I stole Willows eslint stuff and seemed to fix it.

**Comment by conrad-vanl** [comment]
We should probably just copy core's eslint stuff over to the template repo

**Comment by conrad-vanl** [comment]
@jordanwade [this](https://github.com/watermarkchurch/theporch-apollos/pull/13/commits/7c4f521f08fda22a55b0080a86b0d8a656620e7d) is what I had to do to fix this for me - not sure why it was working for you.

Essentially it was weird. You were calling the hook in the body of this function, and rendering the `Provider` the hook depended on in the return statement. I'm not sure what the expected thing was to happen.

**Pull request merged**
