### PR TITLE
Adds navigation action to feature system

### PR DESCRIPTION
**Pull request by vinnyjth**

### CODE REVIEW

**Comment by vinnyjth** [comment]
Still have some refinements to make ensuring that you navigate anywhere in the app safely. @conrad-vanl - let me know your thoughts.

**Comment by conrad-vanl** [comment]
@vinnyjth does this still need to be merged? I merged your other PR hooking up this same button???

**Comment by vinnyjth** [comment]
@conrad-vanl nope, this is dead.

**Pull request closed without merging**
