### PR TITLE
Action List styling

### PR DESCRIPTION
**Pull request by christinamegura**
This PR moves the title outside of the `ActionList` by creating a one-off default prop for `ActionListFeatureWithActionListComponent` that allows the ability to override `ActionListFeature`.

|Before|Home|Discover|
|---|---|---|
|iOS|Simulator Screen Shot - iPhone 11 Pro - 2020-11-04 at 12 18 44|Simulator Screen Shot - iPhone 11 Pro - 2020-11-04 at 12 18 56|

|After|Home|Discover|
|---|---|---|
|iOS|Simulator Screen Shot - iPhone 11 Pro - 2020-11-04 at 12 08 27|Simulator Screen Shot - iPhone 11 Pro - 2020-11-04 at 12 08 34|
|Android|Screenshot_1604510900|Screenshot_1604510910|

### CODE REVIEW

**Comment by conrad-vanl** [comment]
How is this going @christinamegura ?

**Comment by christinamegura** [comment]
Going to open this up today @conrad-vanl

**Comment by conrad-vanl** [comment]
@christinamegura code looks good.

@vinnyjth, I guess "ActionList" doesn't have an outside title available in core like other features do. I guess that makes sense. @vinnyjth what do you think about merging this in, are you okay with taking on this debt of having this localized component?

**Comment by vinnyjth** [comment]
> I guess "ActionList" doesn't have an outside title available in core like other features do. I guess that makes sense. @vinnyjth what do you think about merging this in, are you okay with taking on this debt of having this localized component?

@conrad-vanl I'm fine with this. In my head, this is either a situation where we would tell a future client "sorry, titles stay inside" or change core to have the title outside the card. 

One big takeaway from this PR that @christinamegura and I talked about was needing to add overrides to the individual `Features` so we could do this w/out needing to pass in a new Feature. That will take a core PR.

**Review by vinnyjth — APPROVED** [review]
Looking good Christina! Thanks!

**Pull request merged**
