### PR TITLE
Livestream

### PR DESCRIPTION
**Pull request by vinnyjth**
I don't have a good way of testing this, because the current livestream message doesn't appear anywhere in the app. We should be sure that it's tied to an active piece of content before the tuesday livestream, or make sure they toggle the attached content live.

### CODE REVIEW

**Comment by conrad-vanl** [comment]
@vinnyjth I added the live stream to the home feed features. Can you take a quick look 👀 and see if this looks good? Otherwise this _seems_ to work. I'm willing to merge and test tonight!

How can I tell if the Media Player Play button works when the content switches to live? It should **just work right**? Even though we use the `WCCMessage` type and not the `WeekendContentItem` type?

**Comment by vinnyjth** [comment]
> How can I tell if the Media Player Play button works when the content switches to live? It should just work right? Even though we use the WCCMessage type and not the WeekendContentItem type?

Assuming the `WCCMessage`content single supports a livestream, I think so! I update the GQL fragments on the client in what are hopefully all the right places. I'll give it another once over to be sure.

**Comment by conrad-vanl** [comment]
@vinnyjth there is no `WCCMessage.liveStream` attribute, fwiw.

On core we really should use a `interface` for `liveStream` instead of inferring from a type. Really, we should probably try to use interfaces for most of our core queries. I wonder if htat's soemthing I can try to squeeze in towards the end of the cycle.

**Comment by conrad-vanl** [comment]
But either way, it looks like the `Live Provider` just uses the root-level live streams query and that appers to work correctly and return the `WCCMessage` type

**Comment by vinnyjth** [comment]
Oh, maybe I'm confused. The piece of content on the livestream is of type `WCCMedia`. Should both `Message` and `Media` support livestreams? I imagine so but i'm not 100% sure.

**Pull request merged**
