### PR TITLE
Integrate Spotify feature on Message and Series

### PR DESCRIPTION
**Pull request by jordanwade**
To test with an actual spotify playlist change the `external_playlist` var to `https://open.spotify.com/embed/user/spotify/playlist/37i9dQZF1DWWvHBEQLnV1N` https://github.com/watermarkchurch/theporch-apollos/blob/e6129555f097ab2ed128d4e52ac9758f46b5a27f/apollos-church-api/src/data/wcc-features/index.js#L26

Screen Shot 2020-05-08 at 10 21 57 AM
Screen Shot 2020-05-08 at 10 21 35 AM

Screen Shot 2020-05-08 at 10 21 35 AM
Screen Shot 2020-05-08 at 10 21 35 AM

### CODE REVIEW

**Comment by jordanwade** [comment]
@vinnyjth should we hold on this merge until core is released with the Webview Feature stuff? Probably don't want to ship this with the canary version, correct?

**Comment by vinnyjth** [comment]
@jordanwade I would actually vote it's okay to ship with a canary version :). Especially in a situation like this. I'll let @conrad-vanl have the final word though.

**Comment by conrad-vanl** [comment]
i;m good with this

**Comment by vinnyjth** [comment]
Looking great! I think you need to update the `yarn.lock` but looking good otherwise

**Comment by jordanwade** [comment]
@vinnyjth updated the lock file, but noticed only the root level lock updates. Do the package level yarn.lock files need updated too? Or are they not necessary since there is a root level one?

**Comment by vinnyjth** [comment]
> updated the lock file, but noticed only the root level lock updates. Do the package level yarn.lock files need updated too? Or are they not necessary since there is a root level one?

I think the ones in the package level files are obsolete per a recent package update :) Looks good now, merge it!

**Pull request merged**
