### PR TITLE
Fix Notification UI

### PR DESCRIPTION
**Pull request by jordanwade**
It seems that notifications still need to be hooked up, but the UI should work as expected when that gets sorted out. The `NotificationsProvider` is commented out. https://github.com/watermarkchurch/theporch-apollos/blob/11a1ca4edfb580f312f8c32584d8ebe040c5fb62/ThePorch/src/Providers.js#L20

preview-full-image
preview-full-image-1

### CODE REVIEW

**Comment by conrad-vanl** [comment]
@vinnyjth would it make sense for you to jump into this PR and hookup Notifications? I didn't realize the provider was commented out?

**Comment by vinnyjth** [comment]
@conrad-vanl  yah - are we using our own OneSignal setup? I'll need someone to push certs on iOS for me, and potentially do some firebase stuff for me on Android.

**Comment by vinnyjth** [comment]
Also I thought I had commented back in all that push provider stuff, but maybe I'm thinking of Grace? 

Edit: Oh, I did! But I didn't push it up because I got blocked with push certs on iOS and firebase stuff on Android. Looks like we are still waiting to know if we can revoke their existing cert.

**Comment by vinnyjth** [comment]
@conrad-vanl @jordanwade Let's merge this without fixing the provider / hooking up notifications. I can handle that in another PR, and we need more setup done first.

**Pull request merged**
