### PR TITLE
Update Android App to build on SDK 31 // Remove Campus Selection

### PR DESCRIPTION
**Pull request by vinnyjth**
Upgraded to the latest possible versions of Apollos Packages, and convinced React Native v60 to build on Android 30

### **Some notes:** 

- Strips out all Campus selector code. Also removes the MapView package because it had issues building on Android 31 
- Updates and patches many Android dependencies to work on RN 60 / Android 31. 
  - Notably, had to override some OneSignal defaults in the AndroidManifest order to comply with Android 31 requirements
  - Some misc gradle package overrides that can be removed if this app is ever upgraded to RN 70+
- Updated Apollos Packages to the last 1.X version.
  - 2.x came with a pretty substantial internal rewrite that removed a lot of the custom functionality the porch uses.
  - We could potentially selectively upgrade a couple of packages, but it would require re-writing the app to use Apollo Client 3.x 

### **Building**

I was able to build the app fine in Android Studio and Xcode **w/ Rosetta**. I did notice an issue that the Android app would fail to launch erratically, but it seemed only to impact development builds, and the issue existed in master for me. 

### **Deploying**

I did not test AppCenter or other deployment pipelines. I don't believe there should be any issues building on AppCenter, though. Happy to test and debug any issues that come up if it's relevant. 

CleanShot 2023-04-04 at 14 50 50@2x

### CODE REVIEW

**Comment by redreceipt** [comment]
I can't get past this error for iOS about google cast

Screenshot 2023-04-21 at 11 07 23 AM

**Comment by redreceipt** [comment]
for android, it's not connecting to metro for me for some reason

Screenshot 2023-04-21 at 1 18 26 PM

**Comment by redreceipt** [comment]
@conrad-vanl if this builds fine for you, I think we can feel ok about it

**Comment by vinnyjth** [comment]
for posterity: the iOS error is solved by running Xcode is Rosetta. The Android error _might_ be fixed by running `adb reverse tcp:8081 tcp:8081`

**Comment by redreceipt** [comment]
got it to build!

Screenshot 2023-05-09 at 6 01 59 PM

**Pull request merged**
